// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggpslkhngmtormusjkfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdncHNsa2huZ210b3JtdXNqa2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNDUwNTgsImV4cCI6MjA2MjkyMTA1OH0.TxxSKvk-J9fB9nrZhnRuKPFzmc4qvLKWVSykuTlS-Z0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);